name: sanrio_motion
description: A cute Sanrio-themed motion design and video effects editing app inspired by Alight Motion.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  video_editor: ^1.3.4
  ffmpeg_kit_flutter_min_gpl: ^5.1.0
  gallery_saver: ^2.3.2
  provider: ^6.0.5
  fl_chart: ^0.63.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/